### ISSUE TITLE
Hide sensitive from config keys

### ISSUE THREAD

**Issue by ummahusla** [dennislapchenko/nobullshitquotes#3]
This is not the right way of di

https://github.com/dennislapchenko/nobullshitquotes/blob/8086be5ad6a2fe1c9525e688262978f98e646d46/config/keys.js#L2

The simple snippet which might help. All you need to do is to add a new env variable like `process.env.MONGO_URI` and remove the actual URI from the GitHub. As it was already exposed here it might be a good idea to regenerate the new URI for the security reasons 🙈

```
if (process.env.NODE_ENV === "production") {
	// production 
} else {
	// development
}
```

**Comment by dennislapchenko** [comment]
it is foken local database my dear. Those credentials were picked with exact reason of not giving a flying bird about it! :) Thanks thooo

**Comment by ummahusla** [comment]
I didn’t noticed that it’s a local DB tbh 😅 but anyway you are famous for leaving credentials in the git

**Comment by dennislapchenko** [comment]
**but anyway you are famous for leaving credentials in the git** brings me warmth! any fame is gud!
